PACKAGE_NAME = "pyisort"
PREFERENCE_FILE_NAME = "Preferences.sublime-settings"
PACKAGE_FILE_NAME = "{PACKAGE_NAME}.sublime-package".format(PACKAGE_NAME=PACKAGE_NAME)
SETTINGS_FILE_NAME = "{PACKAGE_NAME}.sublime-settings".format(PACKAGE_NAME=PACKAGE_NAME)
DEFAULT_ENCODING = "UTF-8"
UNDEFINED_ENCODING = "Undefined"
